FROM python:3.12-slim

WORKDIR /dolphin-jo.ru

COPY . /dolphin-jo.ru

RUN python3 -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]